[package]
name = "atproto-client"
version = "0.15.0-alpha.1"
description = "HTTP client for AT Protocol services with OAuth and identity integration"
readme = "README.md"
homepage = "https://tangled.org/ngerakines.me/atproto-crates"
documentation = "https://docs.rs/atproto-client"

edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "atproto-client-app-password"
test = false
bench = false
doc = true
required-features = ["clap"]

[[bin]]
name = "atproto-client-auth"
test = false
bench = false
doc = true
required-features = ["clap"]

[[bin]]
name = "atproto-client-dpop"
test = false
bench = false
doc = true
required-features = ["clap"]

[[bin]]
name = "atproto-client-put-record"
test = false
bench = false
doc = true

[dependencies]
atproto-identity.workspace = true
atproto-oauth.workspace = true
atproto-record.workspace = true

anyhow.workspace = true
reqwest-chain.workspace = true
reqwest-middleware.workspace = true
reqwest.workspace = true
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
urlencoding.workspace = true
async-trait.workspace = true
bytes.workspace = true
clap = { workspace = true, optional = true }
rpassword = { workspace = true, optional = true }
secrecy = { workspace = true, optional = true }

[features]
default = ["hickory-dns"]
clap = ["dep:clap", "dep:rpassword", "dep:secrecy"]
hickory-dns = ["atproto-identity/hickory-dns", "atproto-oauth/hickory-dns"]

[lints]
workspace = true
