//! Build script: exposes `BUILD_REV` to the binary so we can stamp it into
//! User-Agent headers, `/xrpc/_health`, OAuth metadata ETag seeds, and asset
//! cache busting (per).
//!
//! Strategy: try `git rev-parse --short=10 HEAD` first; on any failure (no
//! git repo, no git binary, etc.) fall back to a build timestamp.
//!
//! Also embeds the vendored lexicon corpus. `lexicons/` is walked and a table
//! of `(nsid, json)` pairs generated, backed by `include_str!` so the schemas
//! live in the binary rather than being read from a filesystem layout the
//! server does not control. The NSID comes from the path --
//! `app/bsky/feed/post.json` is `app.bsky.feed.post` -- which matches the `id`
//! field in every one of the vendored documents; reading the JSON here would
//! mean a serde dependency in the build graph to learn what the layout already
//! states.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../../.git/HEAD");

    let rev = git_rev().unwrap_or_else(build_timestamp);
    println!("cargo:rustc-env=BUILD_REV={}", rev);

    generate_lexicon_table();
}

/// Walk `lexicons/` and write the `BUNDLED_LEXICONS` table into `OUT_DIR`.
fn generate_lexicon_table() {
    let manifest =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set"));
    let root = manifest.join("lexicons");
    println!("cargo:rerun-if-changed=lexicons");

    let mut found = BTreeMap::new();
    collect_lexicons(&root, &root, &mut found);

    let mut generated = String::from(
        "// Generated by build.rs from the vendored `lexicons/` corpus. Do not edit.\n\
         /// Every bundled lexicon, as `(nsid, document json)`, sorted by NSID.\n\
         pub static BUNDLED_LEXICONS: &[(&str, &str)] = &[\n",
    );
    for (nsid, path) in &found {
        generated.push_str(&format!(
            "    ({nsid:?}, include_str!({:?})),\n",
            path.to_string_lossy()
        ));
    }
    generated.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR is set"))
        .join("bundled_lexicons.rs");
    std::fs::write(&out, generated).expect("write the generated lexicon table");
}

fn collect_lexicons(dir: &Path, root: &Path, out: &mut BTreeMap<String, PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_lexicons(&path, root, out);
        } else if path.extension().is_some_and(|e| e == "json") {
            let Ok(rel) = path.strip_prefix(root) else {
                continue;
            };
            let nsid = rel
                .with_extension("")
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join(".");
            out.insert(nsid, path.clone());
        }
    }
}

fn git_rev() -> Option<String> {
    let output = Command::new("git")
        .args(["rev-parse", "--short=10", "HEAD"])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let s = String::from_utf8(output.stdout).ok()?;
    let trimmed = s.trim();
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed.to_string())
    }
}

fn build_timestamp() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    format!("ts{}", secs)
}
