[package]
name = "atpxrpc"
version = "0.15.0-rc.1"
description = "AT Protocol XRPC client with persistent session management"
homepage = "https://tangled.org/ngerakines.me/atproto-crates"
documentation = "https://docs.rs/atpxrpc"

edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
atproto-client.workspace = true
atproto-identity = { workspace = true, features = ["hickory-dns"] }

anyhow.workspace = true
bytes.workspace = true
clap.workspace = true
dirs.workspace = true
reqwest.workspace = true
rpassword.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
