[package]
name = "atproto-xrpcs-helloworld"
version = "0.14.1"
description = "Complete example implementation of an AT Protocol XRPC service with DID web functionality and JWT authentication"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "atproto-xrpcs-helloworld"
path = "src/main.rs"
test = false
bench = false
doc = true
required-features = ["clap"]

[dependencies]
atproto-identity.workspace = true
atproto-record.workspace = true
atproto-oauth.workspace = true
atproto-xrpcs.workspace = true

anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
elliptic-curve.workspace = true
hickory-resolver.workspace = true
rand.workspace = true
reqwest-chain.workspace = true
reqwest-middleware.workspace = true
reqwest.workspace = true
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
axum.workspace = true
http.workspace = true
clap = { workspace = true, optional = true }

[features]
default = ["hickory-dns"]
clap = ["dep:clap"]
hickory-dns = ["atproto-identity/hickory-dns", "atproto-oauth/hickory-dns", "atproto-xrpcs/hickory-dns"]

[lints]
workspace = true
