-- The index `listRepos` needs to answer one page instead of scanning a space.
--
-- `listRepos` returns the writer set: the distinct issuers seen in this
-- space's inbound receipt log, each with its latest `rev` and the `set_hash`
-- from that same row. It filters `space = ? AND issuer_did > ?` and correlates
-- `MAX(rev)` per issuer.
--
-- The table had `PRIMARY KEY (space, rev, nsid)` and an index on
-- `(space, received_at)`, and neither can seek on `issuer_did`. The outer
-- query therefore read every row in the space, the correlated subquery read
-- every row in the space again for each of those, and `GROUP BY` went through
-- a temp b-tree that had to be filled before `LIMIT` could take its hundred
-- rows -- so page cost scaled with the size of the space, and quadratically at
-- that.
--
-- `rev DESC` is what makes the subquery a covering seek: the first index entry
-- for an issuer is its latest rev, and `set_hash` rides along in the index, so
-- neither half of the query touches the table.
--
-- Measured on 2,000 issuers x 10 receipts (20k rows), one page of 100:
-- 3.63s before, 0.009s after. At 20,000 issuers (200k rows) it stays at
-- 0.008s, because the work is now the page rather than the space.
CREATE INDEX idx_space_received_op_issuer
    ON space_received_op(space, issuer_did, rev DESC);
