//! Language tag syntax validation
//!
//! Validates BCP 47 / RFC 5646 language tag strings.

use std::sync::LazyLock;

use regex::Regex;

use crate::validation::data_errors::DataValidationError;

/// The RFC 5646 `Language-Tag` grammar.
///
/// Ported from the reference (`packages/syntax/src/language.ts`). The three
/// alternatives at the top level are what a hand-rolled
/// "two-or-three letters, then subtags" pattern misses:
///
/// 1. **`grandfathered`** — irregular tags registered before the grammar
///    settled (RFC 5646 §2.2.8). `i-default` and `i-navajo` are valid and are
///    not generated by any production; they have to be listed.
/// 2. **`langtag`** — the ordinary form, with its subtags positional rather
///    than interchangeable: a 4-letter subtag is a script, a 2-letter or
///    3-digit one is a region, and so on. Treating every subtag as
///    `[a-zA-Z0-9]{1,8}` accepts strings no consumer can interpret.
/// 3. **`privateUseB`** — a tag that is nothing but private use, `x-...`. The
///    singleton is case-insensitive (§2.1.1), so `X-fr-CH` is valid.
static BCP47_REGEX: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"^((?P<grandfathered>(en-GB-oed|i-ami|i-bnn|i-default|i-enochian|i-hak|i-klingon|i-lux|i-mingo|i-navajo|i-pwn|i-tao|i-tay|i-tsu|sgn-BE-FR|sgn-BE-NL|sgn-CH-DE)|(art-lojban|cel-gaulish|no-bok|no-nyn|zh-guoyu|zh-hakka|zh-min|zh-min-nan|zh-xiang))|((?P<language>([A-Za-z]{2,3}(-(?P<extlang>[A-Za-z]{3}(-[A-Za-z]{3}){0,2}))?)|[A-Za-z]{4}|[A-Za-z]{5,8})(-(?P<script>[A-Za-z]{4}))?(-(?P<region>[A-Za-z]{2}|[0-9]{3}))?(-(?P<variant>[A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3}))*(-(?P<extension>[0-9A-WY-Za-wy-z](-[A-Za-z0-9]{2,8})+))*(-(?P<privateUseA>[xX](-[A-Za-z0-9]{1,8})+))?)|(?P<privateUseB>[xX](-[A-Za-z0-9]{1,8})+))$",
    )
    .expect("BCP 47 regex should compile")
});

/// The primary language subtag must be a lowercase two- or three-letter code.
///
/// RFC 5646 §2.1.1 only *recommends* lowercase, so the grammar above admits
/// `JA`, and admits a bare four-letter run like `jaja` through its
/// reserved-for-future-use `[A-Za-z]{4}` alternative. The interop suite treats
/// both as invalid, and this is the rule that says so.
///
/// A grandfathered or private-use-only tag captures no `language` group, so
/// there is nothing to check and it passes.
static STRICT_PRIMARY: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^[a-z]{2,3}$").expect("primary subtag regex should compile"));

/// Validate a BCP 47 language tag.
///
/// Accepts ordinary tags (`en`, `en-US`, `zh-Hans-CN`), the registered
/// grandfathered tags, and private-use tags.
///
/// A repeated variant or extension singleton — `de-DE-1901-1901` — is
/// deliberately **accepted**. Such a tag is well-formed and only fails the
/// *parse* step in the reference, where `isValidLanguage` returns true and
/// only `parseLanguageString` returns null. This is the syntax check, so it
/// answers the syntax question.
///
/// # Errors
///
/// [`DataValidationError::StringFormatInvalid`] naming the rule that failed.
pub fn validate_language(value: &str) -> Result<(), DataValidationError> {
    if value.is_empty() {
        return Err(DataValidationError::StringFormatInvalid {
            format: "language".to_string(),
            value: value.to_string(),
            reason: "language tag cannot be empty".to_string(),
        });
    }

    let Some(captures) = BCP47_REGEX.captures(value) else {
        return Err(DataValidationError::StringFormatInvalid {
            format: "language".to_string(),
            value: value.to_string(),
            reason: "language tag must be a valid BCP 47 tag".to_string(),
        });
    };

    if let Some(language) = captures.name("language") {
        let primary = language.as_str().split('-').next().unwrap_or_default();
        if !STRICT_PRIMARY.is_match(primary) {
            return Err(DataValidationError::StringFormatInvalid {
                format: "language".to_string(),
                value: value.to_string(),
                reason: "the primary language subtag must be two or three lowercase letters"
                    .to_string(),
            });
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_valid_language_tags() {
        let valid = [
            "en",
            "en-US",
            "pt-BR",
            "zh-Hans",
            "zh-Hans-CN",
            "de",
            "fr-FR",
            "ja",
            "ko",
        ];
        for lang in valid {
            assert!(validate_language(lang).is_ok(), "should be valid: {}", lang);
        }
    }

    #[test]
    fn test_invalid_language_tags() {
        let invalid = ["", "e", "123", "en_US", "toolongsubtag-exceeds"];
        for lang in invalid {
            assert!(
                validate_language(lang).is_err(),
                "should be invalid: {}",
                lang
            );
        }
    }

    /// Grandfathered irregular tags (RFC 5646 §2.2.8) are valid and are not
    /// produced by any grammar rule, so they only pass if listed.
    #[test]
    fn grandfathered_tags_are_accepted() {
        for lang in [
            "i-default",
            "i-navajo",
            "zh-hakka",
            "art-lojban",
            "en-GB-oed",
        ] {
            assert!(validate_language(lang).is_ok(), "should be valid: {lang}");
        }
    }

    /// The private-use singleton is case-insensitive (RFC 5646 §2.1.1), so
    /// `X-` is as good as `x-`.
    #[test]
    fn private_use_tags_are_accepted_in_either_case() {
        for lang in ["x-fr-CH", "X-fr-CH", "qaa-Qaaa-QM-x-southern"] {
            assert!(validate_language(lang).is_ok(), "should be valid: {lang}");
        }
    }

    /// The case-insensitivity above stops at the private-use singleton.
    ///
    /// An uppercase *primary* subtag is refused, and so is a bare four-letter
    /// run, which the grammar admits through its reserved-for-future-use
    /// alternative. Both would slip through a regex-only check.
    #[test]
    fn the_primary_subtag_must_be_two_or_three_lowercase_letters() {
        for lang in ["JA", "jaja", "En", "ENG"] {
            assert!(
                validate_language(lang).is_err(),
                "should be invalid: {lang}"
            );
        }
        assert!(validate_language("ja").is_ok());
        assert!(validate_language("eng").is_ok());
    }

    /// Subtags are positional, not interchangeable.
    ///
    /// The previous pattern accepted any `-[a-zA-Z0-9]{1,8}` run after the
    /// primary subtag, so strings with no interpretation passed.
    #[test]
    fn subtag_positions_are_enforced() {
        assert!(validate_language("zh-Hans-CN").is_ok());
        assert!(validate_language("en-419").is_ok(), "numeric region");
        // A 1-letter subtag is an extension singleton and needs a value.
        assert!(validate_language("en-a").is_err());
        assert!(validate_language("a-DE").is_err());
    }

    /// A repeated variant subtag is well-formed and is accepted here.
    ///
    /// The reference draws the line in the same place: `isValidLanguage`
    /// returns true and only `parseLanguageString` returns null. Rejecting it
    /// would make this validator stricter than the network.
    #[test]
    fn a_repeated_variant_subtag_is_still_well_formed() {
        assert!(validate_language("de-DE-1901-1901").is_ok());
    }
}
