[package]
name = "atpmcp"
version = "0.15.0-rc.1"
description = "AT Protocol MCP server for DAG-CBOR CID generation"
homepage = "https://tangled.org/ngerakines.me/atproto-crates"
documentation = "https://docs.rs/atpmcp"

edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "atpmcp"
path = "src/main.rs"
bench = false
doc = true

[dependencies]
atproto-client.workspace = true
atproto-dasl.workspace = true
atproto-extras = { workspace = true, features = ["hickory-dns"] }
atproto-identity = { workspace = true, features = ["hickory-dns"] }
atproto-lexicon = { workspace = true, features = ["panproto"] }
atproto-record.workspace = true

dirs.workspace = true
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
reqwest.workspace = true
rpassword.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
