[package]
name = "atproto-oauth-aip"
version = "0.14.5"
description = "ATProtocol AIP OAuth tools"
readme = "README.md"
homepage = "https://tangled.org/ngerakines.me/atproto-crates"
documentation = "https://docs.rs/atproto-oauth-aip"

edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
atproto-oauth.workspace = true
atproto-identity.workspace = true

anyhow.workspace = true
chrono.workspace = true
reqwest.workspace = true
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true

zeroize = { workspace = true, optional = true }

[features]
default = ["hickory-dns"]
zeroize = ["dep:zeroize", "atproto-oauth/zeroize"]
hickory-dns = ["atproto-oauth/hickory-dns"]

[lints]
workspace = true
