[package]
name = "atproto-jetstream"
version = "0.14.4"
description = "AT Protocol Jetstream event consumer library with WebSocket streaming and compression support"
readme = "README.md"
homepage = "https://tangled.org/ngerakines.me/atproto-crates"
documentation = "https://docs.rs/atproto-jetstream"

edition.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "atproto-jetstream-consumer"
test = false
bench = false
doc = true
required-features = ["clap"]

[dependencies]
tokio = { workspace = true, features = ["sync", "time"] }
tokio-util.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
zstd.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, optional = true }
async-trait.workspace = true
atproto-identity.workspace = true
urlencoding.workspace = true
tokio-websockets.workspace = true
http.workspace = true
clap = { workspace = true, optional = true }

[features]
default = ["hickory-dns"]
clap = ["dep:clap", "dep:tracing-subscriber", "tokio/signal"]
hickory-dns = ["atproto-identity/hickory-dns"]

[lints]
workspace = true
